"""The Neo4j catalog graph: model, idempotent schema, provenanced upserts, retrieval (T-012).

The layer T-020…T-024 write into and T-031 reads from. Four modules, four jobs:

* :mod:`ingest.graph.model` — labels, edge types, node payloads, content-hashed stable IDs.
* :mod:`ingest.graph.schema` — ``IF NOT EXISTS`` constraints on every stable ID plus D6's
  1024-d cosine ``product_embedding`` index.
* :mod:`ingest.graph.upsert` — every write takes a required ``source``, and
  :func:`~ingest.graph.upsert.provenance_violations` audits the result.
* :mod:`ingest.graph.query` — vector **and** attribute candidate retrieval; a request with
  neither raises rather than falling back to a name scan.

Typical use::

    from ingest.graph import Source, Product, apply_schema, upsert_product

    apply_schema(session)
    src = Source("src-1", "https://store.example/p/1", "sha256:…", "2026-01-01T00:00:00Z",
                 "adapter@1", 0.9, "scraped")
    upsert_product(session, Product("p-1", "Gentle Vitamin C Serum", brand="Acme"),
                   source=src)

D38: Neo4j Community has exactly one database, so isolation is scheduler serialization plus
the ``/tmp/proxyshop-neo4j.lock`` flock the root ``conftest.py`` takes — not tenant scoping.
Nothing in this package is tenant-parameterised, deliberately.
"""

from __future__ import annotations

from .model import (
    EMBEDDING_PROPERTY,
    ID_PROPERTY,
    MATERIAL_FACT_EDGES,
    MATERIAL_FACT_LABELS,
    SOURCE_CLASSES,
    SOURCE_ID_PROPERTY,
    SUPPORTED_BY,
    VOCABULARY_LABELS,
    AttributeValue,
    Category,
    Ingredient,
    IntentCluster,
    InvalidEmbeddingVector,
    MediaAsset,
    Offer,
    PolicyPage,
    Product,
    Source,
    Store,
    Variant,
    attribute_value_id,
    canonical_text,
    category_id,
    embedding_vector_defect,
    ingredient_id,
    slug,
)
from .query import (
    DEFAULT_OVERSAMPLE,
    DEFAULT_ROSTER_PRODUCTS,
    AttributeFilter,
    Candidate,
    EmbeddingIndexEmpty,
    EmbeddingProviderMismatch,
    EmbeddingRunIncomplete,
    RosterExclusion,
    ShopCandidate,
    ShopOffer,
    UnretrievableQuery,
    VectorIndexUnusable,
    candidate_products,
    candidate_shops,
    cosine_from_score,
    products_missing_embeddings,
    products_missing_status,
    roster_provenance_exclusions,
)
from .reembed import (
    ReembedReport,
    embed_products,
    embedding_text,
    graph_driver,
    reembed_products,
)
from .schema import (
    ADAPTER_LOOKUP_INDEXES,
    EMBEDDING_RUN_COMPLETE,
    EMBEDDING_RUN_DEGRADED,
    EMBEDDING_RUN_FINISHED_STATES,
    EMBEDDING_RUN_LABEL,
    EMBEDDING_RUN_RUNNING,
    LOOKUP_INDEXES,
    QUERY_PREDICATE_INDEXES,
    VECTOR_INDEX_DIMENSIONS,
    VECTOR_INDEX_NAME,
    VECTOR_INDEX_SIMILARITY,
    VECTOR_INDEX_STATEMENT,
    EmbeddingRun,
    SchemaReport,
    apply_schema,
    await_indexes,
    constraint_name,
    constraint_statements,
    embedding_run,
    lookup_index_statements,
    rebuild_vector_index,
    record_embedding_run,
    schema_report,
    schema_statements,
    vector_index_statement,
)
from .upsert import (
    EmbeddingDimensionMismatch,
    ProvenanceRequired,
    ProvenanceViolation,
    assert_provenance_complete,
    clear_product_embedding,
    link_category,
    link_compatible_with,
    link_ingredient,
    link_same_as,
    link_sells,
    link_states,
    provenance_violations,
    seed_products,
    set_product_embedding,
    upsert_attribute,
    upsert_category,
    upsert_ingredient,
    upsert_intent_cluster,
    upsert_media_asset,
    upsert_offer,
    upsert_policy_page,
    upsert_product,
    upsert_source,
    upsert_store,
    upsert_variant,
)

__all__ = [
    "DEFAULT_OVERSAMPLE",
    "DEFAULT_ROSTER_PRODUCTS",
    "EMBEDDING_PROPERTY",
    "EMBEDDING_RUN_COMPLETE",
    "EMBEDDING_RUN_DEGRADED",
    "EMBEDDING_RUN_FINISHED_STATES",
    "EMBEDDING_RUN_LABEL",
    "EMBEDDING_RUN_RUNNING",
    "ADAPTER_LOOKUP_INDEXES",
    "ID_PROPERTY",
    "LOOKUP_INDEXES",
    "QUERY_PREDICATE_INDEXES",
    "MATERIAL_FACT_EDGES",
    "MATERIAL_FACT_LABELS",
    "SOURCE_CLASSES",
    "SOURCE_ID_PROPERTY",
    "SUPPORTED_BY",
    "VECTOR_INDEX_DIMENSIONS",
    "VECTOR_INDEX_NAME",
    "VECTOR_INDEX_SIMILARITY",
    "VECTOR_INDEX_STATEMENT",
    "VOCABULARY_LABELS",
    "AttributeFilter",
    "AttributeValue",
    "Candidate",
    "Category",
    "EmbeddingDimensionMismatch",
    "EmbeddingIndexEmpty",
    "EmbeddingProviderMismatch",
    "EmbeddingRun",
    "EmbeddingRunIncomplete",
    "Ingredient",
    "IntentCluster",
    "InvalidEmbeddingVector",
    "Offer",
    "PolicyPage",
    "Product",
    "ProvenanceRequired",
    "ProvenanceViolation",
    "ReembedReport",
    "RosterExclusion",
    "SchemaReport",
    "ShopCandidate",
    "MediaAsset",
    "ShopOffer",
    "Source",
    "Store",
    "UnretrievableQuery",
    "Variant",
    "VectorIndexUnusable",
    "apply_schema",
    "assert_provenance_complete",
    "attribute_value_id",
    "await_indexes",
    "candidate_products",
    "candidate_shops",
    "canonical_text",
    "category_id",
    "clear_product_embedding",
    "constraint_name",
    "constraint_statements",
    "cosine_from_score",
    "embedding_run",
    "embedding_text",
    "embedding_vector_defect",
    "graph_driver",
    "ingredient_id",
    "link_category",
    "link_compatible_with",
    "link_ingredient",
    "link_same_as",
    "link_sells",
    "link_states",
    "lookup_index_statements",
    "products_missing_embeddings",
    "products_missing_status",
    "provenance_violations",
    "rebuild_vector_index",
    "record_embedding_run",
    "roster_provenance_exclusions",
    "embed_products",
    "reembed_products",
    "schema_report",
    "schema_statements",
    "seed_products",
    "set_product_embedding",
    "slug",
    "upsert_attribute",
    "upsert_category",
    "upsert_ingredient",
    "upsert_intent_cluster",
    "upsert_media_asset",
    "upsert_offer",
    "upsert_policy_page",
    "upsert_product",
    "upsert_source",
    "upsert_store",
    "upsert_variant",
    "vector_index_statement",
]
